# Generated by Django 4.2.3 on 2023-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_book_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
    ]
