# Generated by Django 4.2.3 on 2023-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_default_to_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
