# Generated by Django 4.2.3 on 2023-08-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
