# Generated by Django 4.2.3 on 2023-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
